train-subset: train_st,train_mt,train_asr 
valid-subset: dev_st

max-epoch: 100
max-update: 30000

num-workers: 4
#patience: 12
no-progress-bar: True
log-interval: 100
seed: 1
report-accuracy: True
best-checkpoint-metric: ppl


arch: s2t_joint_l2g_mustc

w2v-path: 
mt-model-path: 
decoder-embed-path: 
optimizer: adam
clip-norm: 10.0
lr-scheduler: inverse_sqrt
warmup-init-lr: 1e-7
warmup-updates: 5000
lr: 3e-4
adam-betas: (0.9,0.98)
adapter-dim: 4096
adapter-dropout: 0.0

ctc-weight: 0.3
share-ctc-embed: true
share-two-encoders: true

use-ctc-shrink: true
lookback: true

use-token-contrastive: true
use-two-contrastive: true

criterion: label_smoothed_cross_entropy_with_w2v_ctc_shrink_joint_kd

label-smoothing: 0.2
contrastive-alpha: 1.0
contrastive-beta: 1.0
contrastive-temperature: 0.1
zero-infinity: true
post-process: sentencepiece
is-shrink: uniq


#wav2vec configuration

use-cnn-module: False
cnn-module-kernel: 31
apply-mask: True
mask-prob: 0.5
mask-channel-prob: 0.25
mask-channel-length: 6
use-ctc-loss: True
add-position-embed: true
add-position-embed-after-ctc: true
adapter-layers: 0
sead-layers: 6
final-dropout: 0.1
freeze-finetune-updates: 3000


conv-kernel-sizes: 5,5
conv-channels: 512
