#! /bin/bash

gpu_num=1

data_dir=data_all_ende_lcrm
#test_subset=(test_p500_update)
#test_subset=(test_p0.9_p500)
test_subset=(tst-COMMON)
#test_subset=(tst-valid)
#test_subset=(dev)

#exp_name=st_sead_pretrain_all_merge_joint_post_pe_mustc_finetuned_large_batch_two_adapter
#exp_name=st_w2v2_mbart_sate_pseudo_tune
#exp_name=st_joint_train_8gpu_ende_2position_posembed_shrink
#exp_name=st_joint_train_8gpu_ende_100position_posembed_L2
#exp_name=st_joint_train_8gpu_ende_100position_posembed_L2_shrink_share_encoders
#exp_name=st_joint_train_8gpu_ende_100position_posembed_share_encoders
#exp_name=st_joint_train_8gpu_ende_100position_posembed_share_encoders_tune
#exp_name=st_joint_train_8gpu_ende_200position_posembed_share_encoders
#exp_name=st_joint_train_8gpu_ende_200position_posembed_share_encoders_tune
#exp_name=st_joint_train_8gpu_ende_200position_posembed_share_encoders_shrink_tune
#exp_name=st_joint_train_8gpu_ende_200position_posembed_shrink_double_ctc_decrease_inverse
#exp_name=st_joint_train_8gpu_ende_1position_posembed_double_ctc_decrease_inverse_bce
#exp_name=st_joint_train_8gpu_ende_word_ctc_shrink
#exp_name=st_joint_train_8gpu_ende_1position_posembed_double_ctc_decrease_inverse_bce
#exp_name=st_joint_train_8gpu_ende_1position_posembed_double_ctc_decrease_inverse_bce_shrink
#exp_name=st_joint_train_8gpu_ende_1position_posembed_double_ctc_decrease_inverse_bce_vote_shrink
#exp_name=st_joint_200position_two_ctc_shrink
#exp_name=st_joint_ctc_cluster_all_nofreeze_shrink_uniq
#exp_name=st_joint_ctc_all_shrink_uniq_zero_word_align_task_relax
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_2
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_silent_tune
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_ban_lookback_bigbatch
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_ban_lookback_bigbatch
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_tune
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_gpt
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_silent_noise_sead
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_silent_noise
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_sead
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_encoder_conv_noise_new
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_new
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_new_sead
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_convall_noise
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_cl_mt
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_check_L2
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_L2_weight_gumble_wostctc
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_L2_weight_gumble_balance
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_rpr
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_rpr_weight_banscale
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_avgmt_weight_checkorder3
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_avgmt_weight_checkorder3
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_maxmt_weight_2048
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_avgmt_weight_1W
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_maxmt_weight_repeat_tune
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_avgmt_weight_5k
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_banscale_maxmt_weight
exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_encoder_conv_noise_banscale_maxmt_weight
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_encoder3_conv3_noise_banscale_maxmt_weight
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_ban_scale_checkorder
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_check
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_ban_scale_checkcl
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_conv_noise_new
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl_encoder_conv_noise_new
#exp_name=st_joint_ctc_all_shrink_uniq_word_align_task_relax_lookback_bigbatch_two_cl

n_average=5
beam_size=8
len_penalty=1.2
max_tokens=15000
dec_model=checkpoint_last.pt
task=joint_triple_pretraining
device=5
export CUDA_VISIBLE_DEVICES=${device}
cmd="./device_run.sh
    --stage 2
    --stop_stage 2
    --gpu_num ${gpu_num}
    --task ${task}
    --exp_name ${exp_name}
    --n_average ${n_average}
    --beam_size ${beam_size}
    --len_penalty ${len_penalty}
    --max_tokens ${max_tokens}
    --dec_model ${dec_model}
    "

if [[ -n ${data_dir} ]]; then
    cmd="$cmd --data_dir ${data_dir}"
fi
if [[ -n ${test_subset} ]]; then
    test_subset=`echo ${test_subset[*]} | sed 's/ /,/g'`
    cmd="$cmd --test_subset ${test_subset}"
fi

echo $cmd
eval $cmd
